### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by MarkrBradley** [miyako/4d-plugin-oauth#1]
We are trying to use your plugin within a 4D v12 DB. The plugin appears to be disabled and none of the commands execute. Is this a MAC only plugin or will it run on Windows. Thanks Mark

**Comment by miyako** [comment]
Hello, I think the libjson DLL is incompatible, I will recompile and submit it ASAP.

**Comment by miyako** [comment]
should be OK by now.

**Comment by MarkrBradley** [comment]
Many thanks for that. Just 1 quick question. Do you have any examples of connecting to OAUTH using your plugin. As you can tell a bit new to OAuth!! Thanks in advance.

**Comment by miyako** [comment]
first thing to know, there are 2 major implementations of OAuth, 1.0a and 2.0.

Twitter uses 1.0a, Facebook uses 2.0.

the difference is that with 1.0a, the client has to do lot of the heavy lifting.
the plugin was designed mainly for this type of OAuth.

sample DB here:

https://github.com/miyako/4d-tips-sign-in-with-twitter

with 2.0, most of the hard work has shifted to the server side, very little to do on the client side.

**Comment by miyako** [comment]
the last response effectively closed the issue.
