### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mgrueny** [miyako/4d-plugin-oauth#2]
Hello, we are trying to use the Plugin in 4D v15.1 64-Bit for MacOSX. but we got a 'license or privilege error'.
I tried to change the architecture to 'universal', but the build failed.
Is it possible to update the Plugin? or ... are there any other hints?
--maik

**Comment by miyako** [comment]
Hello,

I didn't update the plugin for 64 bits,
since 4D now support JSON, UUID, and some other features originally offered by the plugin.

which commands do you use exactly?

> 2016/02/05 2:03、Maik Grünewald notifications@github.com のメール：
> 
> Hello, we are trying to use the Plugin in 4D v151 64-Bit for MacOSX but we got a 'license or privilege error'
> I tried to change the architecture to 'universal', but the build failed
> Is it possible to update the Plugin? or are there any other hints?

**Comment by mgrueny** [comment]
json ist replaced already. for now only md5 is left.

**Comment by ArminDeeg** [comment]
An update to keep the plugin usable in the future would be nice. We use this commands:

PATH From user selection 
cURL 
cURL Escape url 
cURL Unescape url 
HMACSHA1 
SYSTEM Get unixtime 
Unzip 

Regards Armin

**Comment by mgrueny** [comment]
curl would be nice.

**Comment by miyako** [comment]
you shouldn't need a plugin for MD5 (or SHA1)
c.f. Generate digest
http://doc.4d.com/4Dv15R2/4D/15-R2/Generate-digest.301-2542870.en.html

> 2016/02/05 21:37、Maik Grünewald notifications@github.com のメール：
> json ist replaced already. for now only md5 is left.

宮古 啓介
セールス・エンジニア

株式会社フォーディー・ジャパン
〒150-0043
東京都渋谷区道玄坂1-10-2 渋谷THビル6F
Tel: 03-6427-8441
Fax: 03-6427-8449

Keisuke.Miyako@4d.com
www.4D.com/JP

**Comment by miyako** [comment]
curl is a now a separate branch.
https://github.com/miyako/4d-plugin-curl

note: you only need 64 bits for v15 or later.

> 2016/02/06 1:19、Maik Grünewald notifications@github.com のメール：
> curl would be nice.
> Reply to this email directly or view it on GitHub.

宮古 啓介
セールス・エンジニア

株式会社フォーディー・ジャパン
〒150-0043
東京都渋谷区道玄坂1-10-2 渋谷THビル6F
Tel: 03-6427-8441
Fax: 03-6427-8449

Keisuke.Miyako@4d.com
www.4D.com/JP

**Comment by miyako** [comment]
> PATH From user selection

"Select document" with the option "File name entry" is the native replacement.

> cURL
> cURL Escape url
> cURL Unescape url
> see https://github.com/miyako/4d-plugin-curl
> 
> SYSTEM Get unixtime
> HMACSHA1
> see https://github.com/miyako/4d-plugin-common-crypto
> 
> Unzip
> see https://github.com/miyako/4d-plugin-zip

宮古 啓介
セールス・エンジニア

株式会社フォーディー・ジャパン
〒150-0043
東京都渋谷区道玄坂1-10-2 渋谷THビル6F
Tel: 03-6427-8441
Fax: 03-6427-8449

Keisuke.Miyako@4d.com
www.4D.com/JP

**Comment by miyako** [comment]
closing issue: the plugin is deprecated.
