### ISSUE TITLE
JSON_Append_real Broken in 4D v17

### ISSUE THREAD

**Issue by iamSathishMohan** [miyako/4d-plugin-oauth#3]
It looks like JSON_Get_real Broken in 4D v17. If we try to append real number to json node it appends 0.

`$json:=JSON New

$firstName:=JSON Append text ($json;"firstName";"Keisuke")
$age:=JSON Append long ($json;"age";38)
$points:=JSON Append real ($json;"points";3.14)
$isImportant:=JSON Append bool ($json;"isImportant";0)
$text:=JSON Export to text($json;JSON_WITHOUT_WHITE_SPACE)

SET TEXT TO PASTEBOARD($text)

JSON CLOSE($json)`

**Result:**
{"firstName":"Keisuke","age":38,"points":0,"isImportant":false}

Could you please address this.

**Comment by miyako** [comment]
Hello, the plugin was written for v12 which had no native JSON support. 
Since v13, there is no reason to keep using it.

**Comment by miyako** [comment]
At the very least you should try https://github.com/miyako/4d-plugin-json instead
